name: Deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      target:
        description: 'Target stage to deploy'
        required: true
        type: choice
        options:
          - dev
          - prod
        default: dev
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TARGET: ${{ github.event.inputs.target || 'dev' }}
    defaults:
      run:
        shell: bash
        working-directory: .
    strategy:
      matrix:
        project: [cms, portfolio]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install go-task/task to run Taskfile commands
        uses: arduino/setup-task@v2
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install dependencies
        run: task installDeps:ci
      - name: Build ${{ matrix.project }}
        run: task build:${{ env.TARGET }} -- ${{ matrix.project }}
      - name: Upload AWS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TARGET }}-${{ matrix.project }}
          path: deployment/aws/.build/${{ env.TARGET }}/${{ matrix.project }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      TARGET: ${{ github.event.inputs.target || 'dev' }}
    strategy:
      matrix:
        project: [cms, portfolio]
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Download AWS artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.TARGET }}-${{ matrix.project }}
          path: deployment/aws/.build/${{ env.TARGET }}/${{ matrix.project }}
