name: Handle pull request
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  handle-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Handle pull request
        uses: ./.github/actions/handle-pull-request
